### PR TITLE
Add bungle config flags

### PR DESCRIPTION
**Pull request by inigomedina**
In case you find problems with charlock_holmes gem when running
bundler for installing CARTO builder, you can run a `bundle config`
with some flags for fixing that issue.

### CODE REVIEW

**Comment by gfiorav** [comment]
Thanks for opening a PR!

When is this binary `/usr/local/opt/icu4c` made available? I'm asking in case you did any previous step to install it.

**Comment by inigomedina** [comment]
I didn't any previous step to install it. It was already installed. In case this is something specific to my OS (Sierra), I could be add a note explaining that if it's not available, `brew install icu4c` should be executed.

**Comment by gfiorav** [comment]
@inigomedina Yes, maybe a mention that that icu4c library is needed and how to install it in case the user doesn't have it would be perfect! If you can update this PR to include that I'll merge it in a heartbeat.

Thanks!

**Comment by inigomedina** [comment]
Thanks @gfiorav. 

Updated.

**Review by gfiorav — CHANGES_REQUESTED** [review]
I think 

_"This **assumes** that you have `icu4c` installed (you can check if it's installed on your system by running `which icu4c` in a terminal). If you don't, you can install it using..."_

is clearer!

**Comment by inigomedina** [comment]
Thanks. Updated.

I didn't see your entire comment, so I didn't include explanation for checking it it's installed. If you think it's really important, I can add it.

**Review by gfiorav — APPROVED** [review]

**Comment by gfiorav** [comment]
Merged! Thanks!

**Pull request merged**
